In [206]:
import yahoo_fin as yf
from yahoo_fin.stock_info import get_data
import time
import datetime
import pandas as pd
from yahoo_fin import stock_info as si

import tensorflow as tf 
import numpy as np
from tensorflow.keras import layers

import concurrent.futures

# getting data

things we did to clean data:

1. shamelessly copy:
https://levelup.gitconnected.com/how-to-get-all-stock-symbols-a73925c16a1b

2. we removed the tickers with $

3. we added exception handeling that tries similer strings to the input (note that this is not implemented on the set itself but when fetching, leading to multiple requsts and potentialy to errors)
4.  we just drop exceptions that are found when getting the data from online  (these are diffrent every day)

# how are we keeping consistency? 
since the avilble stocks may change depending on the source of the data some extra steps need to be done in order to
alow saves to work seemlesly 


basic plan:

1. clean the data as much as possible 

2. save the embedings weights with their ticker string

3. backup everything on git to alow us to fix it



In [207]:
df1 = pd.DataFrame( si.tickers_sp500() )
df2 = pd.DataFrame( si.tickers_nasdaq() )
df3 = pd.DataFrame( si.tickers_dow() )
df4 = pd.DataFrame( si.tickers_other() )

sym1 = set( symbol for symbol in df1[0].values.tolist() )
sym2 = set( symbol for symbol in df2[0].values.tolist() )
sym3 = set( symbol for symbol in df3[0].values.tolist() )
sym4 = set( symbol for symbol in df4[0].values.tolist() )

symbols = set.union( sym1, sym2, sym3, sym4 )
del(sym1, sym2, sym3, sym4,df1, df2, df3, df4)

In [208]:
my_list = ['W', 'R', 'P', 'Q']
del_set = set()
sav_set = set()

for symbol in symbols:
    if (len( symbol ) > 4 and symbol[-1] in my_list or "$" in symbol):
        del_set.add( symbol )
    else:
        sav_set.add( symbol )
sav_set.discard("") 

ticker_list=list(sav_set)

print( f'Removed {len( del_set )} unqualified stock symbols...' )
print( f'There are {len( sav_set )} qualified stock symbols...' )

Removed 1583 unqualified stock symbols...
There are 10627 qualified stock symbols...


In [209]:
start='01/01/2020' 
end='09/14/2022'

In [210]:
import concurrent.futures 

def get_seiries(ticker,start,end,entry="adjclose"):
    try:
        raw = get_data(ticker.split(".")[0], start_date=start, end_date=end)[entry]
    except: 
        try:
            raw = get_data(ticker.replace(".","-"), start_date=start, end_date=end)[entry]
        except:
            raw = get_data(ticker[0:4], start_date=start, end_date=end)[entry]
    return raw/raw[0]

def get_df(l,start,end,entry="adjclose"):
    with concurrent.futures.ThreadPoolExecutor() as executor:
        x=[executor.submit(lambda x: get_seiries(x,start,end,entry=entry),name)for name in l]
        x=[a.result() for a in x]
    for i,c in enumerate(x):
        c.name=l[i]
    return pd.DataFrame(x).transpose()

def tester_func(name,start=start,end=end,entry="adjclose"):
    try:
        c= get_seiries(name,start,end,entry)
        c.name=name
        return (True,c)
    except:
        return (False,name)

In [211]:
mini=ticker_list
errors=[]
data=[]
c=0
x=list(range(len(mini)))
with concurrent.futures.ThreadPoolExecutor() as executor:
    for i in range(len(mini)):
        x[i]=executor.submit(tester_func,mini[i])
    
    print("thread setup complete")
    
    for i in range(len(mini)):
        if(i%100==0):
            print(i)
        r=x[i].result()
        if (r[0]): 
            data.append(r[1])
        else:
            errors.append(r[1])
            c+=1
            print(f"error number {c}: name={errors[-1]}")

print("done")

thread setup complete
0
100
error number 1: name=ZAZZT
200
error number 2: name=XTWY
error number 3: name=XTEN
300
400
500
error number 4: name=ZTEST
600
700
error number 5: name=CTEST.G
800
error number 6: name=ZVZZT
900
1000
1100
error number 7: name=IBO
1200
1300
1400
error number 8: name=EMP
error number 9: name=TAFI
error number 10: name=XFIV
error number 11: name=OAIM
1500
error number 12: name=XSVN
1600
error number 13: name=CTEST
1700
1800
1900
2000
error number 14: name=LNKB
2100
2200
error number 15: name=XONE
2300
2400
error number 16: name=ZXZZT
2500
error number 17: name=CTEST.O
2600
2700
2800
2900
error number 18: name=ZBZX
3000
3100
error number 19: name=EAI
error number 20: name=YEAR
3200
error number 21: name=CBX
error number 22: name=ZVZZC
error number 23: name=AMPX
3300
error number 24: name=ATEST.C
3400
3500
3600
error number 25: name=ATEST.A
3700
error number 26: name=CTEST.E
3800
error number 27: name=ZXYZ.A
3900
error number 28: name=CBO
4000
error number 29: nam

In [220]:
data_df=pd.DataFrame(data).transpose()
data_df

KNX      ISRA       SAH      SINT      DMYS       ESI  \
2020-01-02  1.000000  1.000000  1.000000  1.000000       NaN  1.000000   
2020-01-03  0.989997  0.988431  0.976478  1.034247       NaN  0.991453   
2020-01-06  0.991349  0.987867  0.943738  1.041096       NaN  0.988889   
2020-01-07  1.008921  0.994357  0.948188  1.150685       NaN  0.999145   
2020-01-08  1.002703  0.997178  0.943738  1.239726       NaN  1.002564   
...              ...       ...       ...       ...       ...       ...   
2022-09-07  1.379588  1.157333  1.613864  0.276027  0.984016  1.646224   
2022-09-08  1.375992  1.163347  1.573082  0.280822  0.985015  1.674304   
2022-09-09  1.407799  1.188550  1.558939  0.284247  0.983017  1.696242   
2022-09-12  1.408352  1.206307  1.622744  0.282192  0.983017  1.717303   
2022-09-13  1.375716  1.165638  1.510921  0.293836  0.983017  1.644469   

                NBCT      ORIA      EGAN       BOC  ...      HWBK      QARP  \
2020-01-02       NaN       NaN  1.000000  1.000000  ...  1.000000  1.000000   
2020-01-03       NaN       NaN  0.988861  1.005145  ...  0.983574  0.990445   
2020-01-06       NaN       NaN  0.974010  1.010290  ...  0.981619  0.993410   
2020-01-07       NaN       NaN  0.960396  1.001871  ...  0.978882  0.992092   
2020-01-08       NaN       NaN  0.972772  1.011693  ...  0.980837  0.996376   
...              ...       ...       ...       ...  ...       ...       ...   
2022-09-07  0.984201  1.023958  1.092822  1.228251  ...  1.026023  1.256502   
2022-09-08  0.987963  1.022917  1.092822  1.210477  ...  1.012500  1.265236   
2022-09-09  0.998258  1.025000  0.936881  1.235267  ...  0.985033  1.287355   
2022-09-12  1.005227  1.022917  0.991337  1.246024  ...  0.993062  1.296527   
2022-09-13  0.981707  1.023958  0.950495  1.216090  ...  0.977426  1.240486   

            CTAQU      IPGP       RYE      OVLY      GOLF      GGLS       BLU  \
2020-01-02    NaN  1.000000  1.000000  1.000000  1.000000       NaN  1.000000   
2020-01-03    NaN  0.968187  1.002291  0.993782  1.010836       NaN  1.063226   
2020-01-06    NaN  0.978086  1.012497  0.991710  1.021053       NaN  1.070968   
2020-01-07    NaN  0.983752  1.021245  0.970466  0.991641       NaN  1.027097   
2020-01-08    NaN  0.983411  0.999792  0.974093  0.990093       NaN  1.032258   
...           ...       ...       ...       ...       ...       ...       ...   
2022-09-07  0.995  0.610117  1.450781  0.984163  1.590106  0.975000  1.504516   
2022-09-08  0.993  0.612916  1.456849  0.976646  1.605000  0.986292  1.516129   
2022-09-09  0.993  0.629301  1.495638  0.976646  1.629284  0.963400  1.501936   
2022-09-12  0.993  0.634558  1.529659  0.971814  1.629932  0.963856  1.477419   
2022-09-13  0.993  0.606226  1.485670  0.970740  1.575212  1.018220  1.406452   

                GMRE  
2020-01-02  1.000000  
2020-01-03  1.018504  
2020-01-06  1.033924  
2020-01-07  1.028527  
2020-01-08  1.043947  
...              ...  
2022-09-07  0.953409  
2022-09-08  0.954295  
2022-09-09  0.967586  
2022-09-12  0.988852  
2022-09-13  0.950751  

[680 rows x 10569 columns]

In [221]:
ticker_list=data_df.columns
print(f"{len(symbols)-len(ticker_list)} stocks were droped")

1642 stocks were droped


# preprocessing 


1. ticker: this is also used to select which stocks come to the model

2. price: we take the ratio: (importantly we did drop some potentialy important indicators)

3. date: the day and month are floating point numbers. while year and day of the week are embedings.



In [222]:
look=layers.StringLookup(vocabulary=ticker_list)
inv_look=layers.StringLookup(vocabulary=ticker_list,invert=True,num_oov_indices=0)
tick_embed=layers.Embedding(len(ticker_list)+1,512,embeddings_constraint= tf.keras.constraints.unit_norm)
day_embed=layers.Embedding(7,10)

In [223]:
dataset=tf.data.Dataset.from_tensor_slices(ticker_list)
exmple=dataset.batch(17).take(1).get_single_element()
exmple

<tf.Tensor: shape=(17,), dtype=string, numpy=
array([b'KNX', b'ISRA', b'SAH', b'SINT', b'DMYS', b'ESI', b'NBCT',
       b'ORIA', b'EGAN', b'BOC', b'APRZ', b'MMAT', b'LDP', b'MKSI',
       b'NLIT', b'GCT', b'CNTQU'], dtype=object)>

In [224]:
#data_df[exmple.numpy().astype('U13')]

In [225]:
def thread_distribute(l,f,n=1):
    if(n==0):
        return f(l)
    
    with concurrent.futures.ThreadPoolExecutor() as executor: 
        l=[executor.submit(lambda x: thread_distribute(x,f,n-1),x) for x in l]
        l= [x.result() for x in l]
    return l

thread_distribute([range(5) for i in range(2)],lambda x: range(x),2)

[[range(0, 0), range(0, 1), range(0, 2), range(0, 3), range(0, 4)],
 [range(0, 0), range(0, 1), range(0, 2), range(0, 3), range(0, 4)]]

In [266]:
def choose_stocks(x):
    a=tick_embed(look(ticker_list))
    b=tick_embed(look(x))

    b=b@tf.transpose(a)
    b=tf.nn.top_k(b,3)


    tickers=inv_look([list(x) for x in b[1].numpy()]).numpy().astype('U13')
    
    return [[data_df[x] for x in sub] for sub in tickers]
    #return thread_distribute(tickers,lambda x: data_df[x],2)

a=choose_stocks(exmple)

pd.DataFrame(a[0]).transpose().dropna()

KNX      IGHG    MACA
2021-04-07  1.356753  1.027899  1.0000
2021-04-08  1.350746  1.028975  1.0180
2021-04-09  1.367401  1.029782  0.9970
2021-04-12  1.366036  1.030321  0.9930
2021-04-13  1.363579  1.029648  0.9953
...              ...       ...     ...
2022-09-07  1.379588  0.973802  0.9910
2022-09-08  1.375992  0.973802  0.9910
2022-09-09  1.407799  0.978283  0.9920
2022-09-12  1.408352  0.977583  0.9920
2022-09-13  1.375716  0.973942  0.9900

[363 rows x 3 columns]

In [265]:
a[0][0].index

DatetimeIndex(['2020-01-02', '2020-01-03', '2020-01-06', '2020-01-07',
               '2020-01-08', '2020-01-09', '2020-01-10', '2020-01-13',
               '2020-01-14', '2020-01-15',
               ...
               '2022-08-30', '2022-08-31', '2022-09-01', '2022-09-02',
               '2022-09-06', '2022-09-07', '2022-09-08', '2022-09-09',
               '2022-09-12', '2022-09-13'],
              dtype='datetime64[ns]', length=680, freq=None)

In [242]:
def time_encode(a):
    #a=a.index
    return (a.day_of_week,a.day/30,a.month/12,(a.year-2020))
    
time_encode(data_df.index[0])

(3, 0.06666666666666667, 0.08333333333333333, 0)

In [243]:
def time_tensors(a):
    x=thread_distribute(a,lambda x:time_encode(x.index),2)
    x=[thread_distribute(x,lambda x: x[i],2) for i in range(4)]
    return [tf.constant(x) for x in x]

time_tensors(a)

[<tf.Tensor: shape=(17, 3, 680), dtype=int32, numpy=
 array([[[3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1]],
 
        [[3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1]],
 
        [[3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1]],
 
        ...,
 
        [[3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1]],
 
        [[3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1]],
 
        [[3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1],
         [3, 4, 0, ..., 4, 0, 1]]])>,
 <tf.Tensor: shape=(17, 3, 680), dtype=float64, numpy=
 array([[[0.06666667, 0.1       , 0.2       , ..., 0.3       ,
          0.4       , 0.43333333],
         [0.06666667, 0.1       , 0.2       , ..., 0.3       ,
          0.4       , 0.43333333],
         [0.06666667, 0.1       , 0.2       , ...,

# time handeling 

problems with the data in curent time format:

1. there are null entries especialy from before a company was made 
2. the time diffrence between entries isnt clean

In [244]:
a[0][0][5:10]

2020-01-09    1.000811
2020-01-10    1.007029
2020-01-13    1.012436
2020-01-14    1.027034
2020-01-15    1.026494
Name: KNX, dtype: float64

In [245]:
data_df[exmple.numpy().astype('U13')]

KNX      ISRA       SAH      SINT      DMYS       ESI  \
2020-01-02  1.000000  1.000000  1.000000  1.000000       NaN  1.000000   
2020-01-03  0.989997  0.988431  0.976478  1.034247       NaN  0.991453   
2020-01-06  0.991349  0.987867  0.943738  1.041096       NaN  0.988889   
2020-01-07  1.008921  0.994357  0.948188  1.150685       NaN  0.999145   
2020-01-08  1.002703  0.997178  0.943738  1.239726       NaN  1.002564   
...              ...       ...       ...       ...       ...       ...   
2022-09-07  1.379588  1.157333  1.613864  0.276027  0.984016  1.646224   
2022-09-08  1.375992  1.163347  1.573082  0.280822  0.985015  1.674304   
2022-09-09  1.407799  1.188550  1.558939  0.284247  0.983017  1.696242   
2022-09-12  1.408352  1.206307  1.622744  0.282192  0.983017  1.717303   
2022-09-13  1.375716  1.165638  1.510921  0.293836  0.983017  1.644469   

                NBCT      ORIA      EGAN       BOC      APRZ      MMAT  \
2020-01-02       NaN       NaN  1.000000  1.000000       NaN  1.000000   
2020-01-03       NaN       NaN  0.988861  1.005145       NaN  1.011111   
2020-01-06       NaN       NaN  0.974010  1.010290       NaN  1.100000   
2020-01-07       NaN       NaN  0.960396  1.001871       NaN  1.166667   
2020-01-08       NaN       NaN  0.972772  1.011693       NaN  1.066667   
...              ...       ...       ...       ...       ...       ...   
2022-09-07  0.984201  1.023958  1.092822  1.228251  1.006034  0.438889   
2022-09-08  0.987963  1.022917  1.092822  1.210477  1.010270  0.444444   
2022-09-09  0.998258  1.025000  0.936881  1.235267  1.020699  0.466667   
2022-09-12  1.005227  1.022917  0.991337  1.246024  1.026853  0.472222   
2022-09-13  0.981707  1.023958  0.950495  1.216090  0.996324  0.455556   

                 LDP      MKSI      NLIT       GCT     CNTQU  
2020-01-02  1.000000  1.000000       NaN       NaN       NaN  
2020-01-03  0.998094  0.963606       NaN       NaN       NaN  
2020-01-06  0.995044  0.947063       NaN       NaN       NaN  
2020-01-07  0.999619  0.972011       NaN       NaN       NaN  
2020-01-08  1.004575  0.967182       NaN       NaN       NaN  
...              ...       ...       ...       ...       ...  
2022-09-07  0.930552  0.881337  1.038462  1.288719  1.050797  
2022-09-08  0.935703  0.889980  1.035931  1.281071  1.050797  
2022-09-09  0.935235  0.912453  1.043522  1.153601  1.045817  
2022-09-12  0.934766  0.911634  1.035425  1.131294  1.045817  
2022-09-13  0.938774  0.855499  1.032389  1.073932  1.045817  

[680 rows x 17 columns]

In [189]:
c=np.array(["KNX","ISRA"])
c.shape

(2,)

In [257]:
na=data_df.isna().any()
na

KNX     False
ISRA    False
SAH     False
SINT    False
DMYS     True
        ...  
OVLY    False
GOLF    False
GGLS     True
BLU     False
GMRE    False
Length: 10569, dtype: bool

In [282]:
pd.DataFrame(a[0]).transpose().dropna()

KNX      IGHG    MACA
2021-04-07  1.356753  1.027899  1.0000
2021-04-08  1.350746  1.028975  1.0180
2021-04-09  1.367401  1.029782  0.9970
2021-04-12  1.366036  1.030321  0.9930
2021-04-13  1.363579  1.029648  0.9953
...              ...       ...     ...
2022-09-07  1.379588  0.973802  0.9910
2022-09-08  1.375992  0.973802  0.9910
2022-09-09  1.407799  0.978283  0.9920
2022-09-12  1.408352  0.977583  0.9920
2022-09-13  1.375716  0.973942  0.9900

[363 rows x 3 columns]

In [275]:
mask=np.logical_not(data_df.isna().to_numpy())
mask

array([[ True,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ..., False,  True,  True],
       [ True,  True,  True, ..., False,  True,  True],
       ...,
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True],
       [ True,  True,  True, ...,  True,  True,  True]])

In [292]:
def choose_stocks_df(x):
    a=tick_embed(look(ticker_list))
    b=tick_embed(look(x))

    b=b@tf.transpose(a)
    b=tf.nn.top_k(b,3)


    tickers=inv_look([list(x) for x in b[1].numpy()]).numpy().astype('U13')
    
    return [pd.DataFrame([data_df[x] for x in sub]).transpose().dropna() for sub in tickers]

v=choose_stocks_df(exmple)
v[0]

KNX      IGHG    MACA
2021-04-07  1.356753  1.027899  1.0000
2021-04-08  1.350746  1.028975  1.0180
2021-04-09  1.367401  1.029782  0.9970
2021-04-12  1.366036  1.030321  0.9930
2021-04-13  1.363579  1.029648  0.9953
...              ...       ...     ...
2022-09-07  1.379588  0.973802  0.9910
2022-09-08  1.375992  0.973802  0.9910
2022-09-09  1.407799  0.978283  0.9920
2022-09-12  1.408352  0.977583  0.9920
2022-09-13  1.375716  0.973942  0.9900

[363 rows x 3 columns]

In [508]:
#it is clear that there isnt perfect index overlap. we need to indecies 1 by 1
#pd.concat(v).index 
t=[x.index for x in v]
t=thread_distribute(t,time_encode,2)
#t=[[x[i] for x in t] for i in range(4)]
t=[thread_distribute(t,lambda x: x[i],2) for i in range(4)]
#thread_distribute(t,len,2)
t=[tf.ragged.constant(x) for x in t]

"padding"
t=[(x+1).to_tensor()-1 for x in t]


[x.dtype for x in t]

[tf.int32, tf.float32, tf.float32, tf.int32]

In [507]:
x=thread_distribute(v,lambda x: x.to_numpy(),1)
vals=tf.concat(x,axis=0)
lengths=[len(s) for s in x]
x=tf.RaggedTensor.from_row_lengths(vals,lengths)
#[x.shape for x in x]
"padding the prices"
x=(x+1).to_tensor()-1
x=tf.transpose(x,[2,0,1])
x.shape

TensorShape([3, 17, 680])

In [510]:
def get_xs(v):
    t=[x.index for x in v]
    t=thread_distribute(t,time_encode,2)
    #t=[[x[i] for x in t] for i in range(4)]
    t=[thread_distribute(t,lambda x: x[i],2) for i in range(4)]
    #thread_distribute(t,len,2)
    t=[tf.ragged.constant(x) for x in t]
    
    x=thread_distribute(v,lambda x: x.to_numpy(),1)
    vals=tf.concat(x,axis=0)
    lengths=[len(s) for s in x]
    x=tf.RaggedTensor.from_row_lengths(vals,lengths)
    #[x.shape for x in x]
    
    "padding"
    x=(x+1).to_tensor()-1
    t=[(x+1).to_tensor()-1 for x in t] 
    
    x=tf.transpose(x,[2,0,1])
    t.extend(x) 
    return t

xs=get_xs(v)
[x.shape for x in xs]

[TensorShape([17, 680]),
 TensorShape([17, 680]),
 TensorShape([17, 680]),
 TensorShape([17, 680]),
 TensorShape([17, 680]),
 TensorShape([17, 680]),
 TensorShape([17, 680])]